extends: spectral:oas

rules:
  info-contact:
    description: API should have contact info
    given: $.info.contact
    severity: warn
    then:
      field: name
      function: truthy

  operation-description:
    description: Operations should have descriptions
    given: $.paths[*][*]
    severity: warn
    then:
      field: description
      function: truthy

  no-ambiguous-schema:
    description: Schemas should have a type
    given: $.components.schemas[*].properties[*]
    severity: warn
    then:
      field: type
      function: truthy
