
openapi: 3.0.3
info:
  title: Webhooks API
  version: "1.0"
paths:
  /webhooks:
    get:
      tags: [Webhooks]
      operationId: listWebhooks
      summary: List all webhook subscriptions
      responses:
        "200":
          description: A list of webhooks
    post:
      tags: [Webhooks]
      operationId: createWebhook
      summary: Register a new webhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Webhook"
      responses:
        "201":
          description: Webhook created
  /webhooks/{id}:
    delete:
      tags: [Webhooks]
      operationId: deleteWebhook
      summary: Unsubscribe from a webhook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted
components:
  schemas:
    Webhook:
      type: object
      properties:
        url:
          type: string
        events:
          type: array
          items:
            type: string
        secret:
          type: string
''',

    "custom_fields.yaml": '''
openapi: 3.0.3
info:
  title: Custom Fields API
  version: "1.0"
paths:
  /custom_fields/templates:
    get:
      tags: [CustomFields]
      operationId: listFieldTemplates
      summary: List custom field templates
      responses:
        "200":
          description: List of templates
  /matters/{id}/custom_fields:
    get:
      tags: [CustomFields]
      operationId: getMatterCustomFields
      summary: Get custom fields for a matter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Custom field values
    post:
      tags: [CustomFields]
      operationId: setMatterCustomFields
      summary: Set custom fields for a matter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: Updated
''',

    "custom_actions.yaml": '''
openapi: 3.0.3
info:
  title: Custom Actions API
  version: "1.0"
paths:
  /matters/{id}/duplicate:
    post:
      tags: [CustomActions]
      operationId: duplicateMatter
      summary: Duplicate a matter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Duplicated
      x-action: true
  /contacts/{id}/send_welcome_email:
    post:
      tags: [CustomActions]
      operationId: sendWelcomeEmail
      summary: Send welcome email to contact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Email sent
      x-action: true
